# Generated by Django 4.2.7 on 2023-12-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskuser',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
