name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install --no-interaction
        pip install -r requirements.txt
        make build

    - name: Run linter
      run: make lint
    - name: Run tests
      env:
        DEVELOPMENT_MODE: ${{ secrets.DEVELOPMENT_MODE }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        make install
        make tests

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        DEVELOPMENT_MODE: ${{ secrets.DEVELOPMENT_MODE }}
      with:
        coverageCommand: make test-coverage
        debug: true