name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: |
        poetry install --no-interaction
        pip install -r requirements.txt
        make build

    - name: Run linter
      run: make lint
    - name: Run tests
      run: make test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v3.2.0
      if: github.ref_name == 'main'
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      with:
        coverageCommand: make test-coverage
        debug: true